spring:
  application:
    name: intensivo-java
  datasource:
    url: jdbc:mysql://localhost:3306/backend?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: root
    password: senha234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
server:
  port: 8080
logging:
  level:
    root: INFO
    com.intensivo.java: INFO
